apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-config
  namespace: rag-prod
data:
  INGEST_AWS_REGION: ${AWS_REGION}
  INGEST_S3_BUCKET: ${S3_BUCKET}
  INGEST_SQS_QUEUE_URL: ${SQS_QUEUE_URL}
